kind: pipeline
name: default

environment:
  DOCKER_PASS:
    from_secret: DOCKER_PASSWORD

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

workspace:
  path: /source

steps:
  - name: buildx
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - ./build.sh
