kind: pipeline
name: default

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

workspace:
  path: /source

steps:
  - name: buildx
    image: docker:dind
    environment:
      DOCKER_PASS:
        from_secret: DOCKER_PASSWORD
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - "chmod +x ./build.sh"
      - "./build.sh"
