kind: pipeline
name: default

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

workspace:
  path: /source

steps:
  - name: buildx
    image: docker:dind
    environment:
      DOCKER_PASS:
        from_secret: DOCKER_PASSWORD
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - 'chmod +x ./build.sh'
      - './build.sh'

  - name: publish-official-readme
    image: chko/docker-pushrm:1
    environment:
      PUSHRM_SHORT: Node 20 and pnpm are preinstalled, compatible with canvas, weekly synchronization.
      PUSHRM_TARGET: docker.io/paperplanecc/baseline-node20
      DOCKER_USER: paperplanecc
      DOCKER_PASS:
        from_secret: DOCKER_PASS
    commands:
      - /docker-pushrm
